language: python
matrix:
  include:
    - python: 3.9
      dist: xenial
      sudo: true

env:
  global:
    - API_ROOT=http://127.0.0.1:5000
    - TOKEN_AUTHOR=171b54871ecf1a08
    - MONGO_URI=mongodb://127.0.0.1/test
    - LISTEN_PORT=5000

services:
  - mongodb
  - docker

before_install:
  - docker pull dhuan/eve-token-auth-demo:testing
  - docker run -d --network=host -e LISTEN_PORT -e MONGO_URI -e TOKEN_AUTHOR dhuan/eve-token-auth-demo:testing
  - docker ps -a

install:
  - python3 setup.py install

script:
  - pytest
