language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - API_ROOT=http://127.0.0.1:5000
    - TOKEN_AUTHOR=171b54871ecf1a08
    - MONGO_URI=mongodb://127.0.0.1/test

services:
  - mongodb
  - docker

before_install:
  - sleep 15
  - docker pull dhuan/eve-token-auth-demo:testing
  - docker run -d --network=host -p 127.0.0.1:80:5000 -e MONGO_URI -e TOKEN_AUTHOR dhuan/eve-token-auth-demo:testing
  - docker ps -a

install:
  - pip install requests

before_script:
  - pwd
  - ls -lah
  - curl http://127.0.0.1:5000

script:
  - pytest
